apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: client-tracker

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - pvc.yaml
  - ollama-deployment.yaml
  - api-deployment.yaml

commonLabels:
  app.kubernetes.io/name: client-tracker
  app.kubernetes.io/managed-by: argocd